/**CREAR FUNCION QUE DADO UN NUMERO CREE ESE NUMERO DE DIVS PERO 
 * CON UN ANCHO Y UN ALTO DE 100PX POR EL ORDEN QUE SE MUESTRA. 
 * TODOS LOS DIVS TIENEN QUE TENER UN BORDE DE 1PX SOLID BLACK.
 * lOS DIVS IMPARES DEBEN TENER COLOR VERDE Y LOS PARE COLOR ROJO.
 * cADA DIV DEBE MOSTARAR SU NUMERO CORRESPONDIENTE CON UN H2 POR EJEMPLO: DIV 1 */

 function creaDivs(numero){

 }